#pragma config(Sensor, in1,    theLPotentio,   sensorPotentiometer)
#pragma config(Sensor, in2,    clawsPotentio,  sensorPotentiometer)
#pragma config(Sensor, in3,    lineFollowerFrontLeft, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerFrontRight, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerBackLeft, sensorLineFollower)
#pragma config(Sensor, in6,    lineFollowerBackRight, sensorLineFollower)
#pragma config(Sensor, in7,    myGyro,         sensorGyro)
#pragma config(Sensor, dgtl2,  craneEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  pushButtonRight, sensorTouch)
#pragma config(Sensor, dgtl5,  pushButtonLeft, sensorTouch)
#pragma config(Sensor, dgtl6,  frontRightEnc,  sensorQuadEncoder)
#pragma config(Motor,  port1,           frontRight,    tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           rightClaw,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           intake,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           theL,          tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftClaw,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           midRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           backLeftExp,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           craneExp,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          frontLeft,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 30      // Default will cause 375mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    256     // essentially off
#define MOTOR_TASK_DELAY        20      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          10
#define MAX_CMD									127

int a,b;
int g = SensorValue[myGyro];
int p = SensorValue[frontRightEnc];
int lffr = SensorValue[lineFollowerFrontRight];
int lffl = SensorValue[lineFollowerFrontLeft];
int lfbr = SensorValue[lineFollowerBackRight];
int lfbl = SensorValue[lineFollowerBackLeft];
int cpot = SensorValue[clawsPotentio];
int lpot = SensorValue[theLPotentio];
int craneval =SensorValue[craneEnc];
int pbl = SensorValue[pushButtonLeft];
int pbr = SensorValue[pushButtonRight];

bool midPost=false ,HighPost=false;


//functions definition
void moveClawsTo(int clawsTar);
void moveClawsWith(int speed);
void moveCraneWith(int speed);
void moveCraneTo(int craneTar);
void moveRobot(int LSpeed, int RSpeed);

//motor controls

int motorReq[MOTOR_NUM];
int motorSlew[MOTOR_NUM];
//Motor Slew Task
task MotorSlewRateTask()
{
	int motorIndex;
	int motorTmp;


	// Initialize stuff
	for (motorIndex = 0; motorIndex < (signed)MOTOR_NUM; motorIndex++)
	{
		motorReq[motorIndex] = 0;
		motorSlew[motorIndex] = MOTOR_DEFAULT_SLEW_RATE;
	}

	// run task until stopped
	while (true)
	{
		// run loop for every motor
		for (motorIndex = 0; motorIndex < (signed)MOTOR_NUM; motorIndex++)
		{
			// So we don't keep accessing the internal storage
			motorTmp = motor[motorIndex];

			// Do we need to change the motor value ?
			if (motorTmp != motorReq[motorIndex])
			{
				// increasing motor value
				if (motorReq[motorIndex] > motorTmp)
				{
					motorTmp += motorSlew[motorIndex];
					// limit
					if (motorTmp > motorReq[motorIndex])
						motorTmp = motorReq[motorIndex];
				}

				// decreasing motor value
				if (motorReq[motorIndex] < motorTmp)
				{
					motorTmp -= motorSlew[motorIndex];
					// limit
					if (motorTmp < motorReq[motorIndex])
						motorTmp = motorReq[motorIndex];
				}

				// finally set motor
				motor[motorIndex] = motorTmp;
			}
		}

		// Wait approx the speed of motor update over the spi bus
		wait1Msec(MOTOR_TASK_DELAY);
	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	startTask(MotorSlewRateTask);

	while (true)
	{
		g=SensorValue[myGyro];
		p=SensorValue[frontRightEnc];
		a = vexRT[Ch2];
		b = vexRT[Ch3];
		 lffr = SensorValue[lineFollowerFrontRight];
 lffl = SensorValue[lineFollowerFrontLeft];
 lfbr = SensorValue[lineFollowerBackRight];
 lfbl = SensorValue[lineFollowerBackLeft];
 cpot = SensorValue[clawsPotentio];
 lpot = SensorValue[theLPotentio];
 craneval =SensorValue[craneEnc];
 pbl = SensorValue[pushButtonLeft];
 pbr = SensorValue[pushButtonRight];
		if(abs(a) < 15){a = 0;}
		if(abs(b) < 15){b = 0;}
		if(a*b < 0){a = 3*a/5;b = 3*b/5;}

		motorReq[frontLeft] = b;
		motorReq[backLeftExp] = b;
		motorReq[frontRight] = a;
		motorReq[backRight] = a;
		motorReq[midRight]=a;

		motorReq[rightClaw] = 0;
		//motorReq[craneExp] = 0;
		motorReq[leftClaw] = 0;
		motorReq[theL] = 0;
		motorReq[intake] = 0;

		if(vexRT[Btn8U]){
			midPost= !midPost;
	}
			//if(vexRT[Btn8D]) motorReq[craneExp] = -127;
		else if(vexRT[Btn8L]){ motorReq[rightClaw] = -127;
			motorReq[leftClaw] = -127;
		}
		else if(vexRT[Btn8R]){ motorReq[rightClaw] = 127;
			motorReq[leftClaw] = 127;
		}
		else if(vexRT[Btn7R]) motorReq[theL] = 120;
		else if(vexRT[Btn7L]) motorReq[theL] = -100;
		else if(vexRT[Btn7U]) motorReq[intake] = -100;

	  else if(vexRT[Btn8R]){
	  	motorReq[rightClaw] = 0;
			motorReq[craneExp] = 0;
			motorReq[leftClaw] = 0;
			motorReq[theL] = 0;
	  }
	 if(midPost){
	   if(craneval<250)
				motorReq[craneExp] =(int) 127 - 1.0*craneval/2000*127 ;
	 }
	 else if (HighPost){

		}
		else
	   if(craneval>10)
	     	motorReq[craneExp]=-100;

	}// EoWhile
}




//methods
void moveRobot(int LSpeed, int RSpeed)
{
	motorReq[frontLeft] = LSpeed;
	motorReq[backLeftExp] = LSpeed;
	motorReq[frontRight] = RSpeed;
	motorReq[midRight] = RSpeed;
	motorReq[backRight] = RSpeed;
}
void moveCraneWith(int speed)
{
	motorReq[craneExp]= speed;
}
void moveCraneTo(int craneTar)
{
	int Errcr = -SensorValue[craneEnc] + craneTar;
	moveCraneWith(1.2*Errcr + 0.00001*IErrc);
	if(abs(1.2*Errcr + 0.00001*IErrc) < MAX_CMD)
	{
		IErrc = IErrc + Errcr;
	}
}
